# Generated by Django 4.0.5 on 2022-06-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesaj',
            options={'verbose_name_plural': 'mesaje'},
        ),
    ]
