# Generated by Django 4.0.5 on 2022-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0002_alter_mesaj_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='country',
            field=models.CharField(choices=[('Au', 'Austria'), ('Ge', 'Germany'), ('Ro', 'Romania')], default='Ro', max_length=2),
        ),
        migrations.AddField(
            model_name='mesaj',
            name='subiect',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
