# Generated by Django 4.0.5 on 2022-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0003_mesaj_country_mesaj_subiect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='country',
            field=models.CharField(choices=[('Au', 'Austria'), ('Ge', 'Germany'), ('Ro', 'Romania')], default='Ro', max_length=3),
        ),
    ]
