# Generated by Django 4.0.5 on 2022-06-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0004_alter_mesaj_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='country',
        ),
        migrations.AddField(
            model_name='mesaj',
            name='tara',
            field=models.CharField(choices=[('Au', 'Austria'), ('Ge', 'Germany'), ('Ro', 'Romania')], default='Ro', max_length=2),
        ),
    ]
