# Generated by Django 4.0.5 on 2022-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0005_remove_mesaj_country_mesaj_tara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='tara',
            field=models.CharField(choices=[('Au', 'Austria'), ('De', 'Germania'), ('Ro', 'Romania'), ('Hu', 'Ungaria')], default='Ro', max_length=2),
        ),
    ]
