# Generated by Django 4.0.5 on 2022-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0006_alter_mesaj_tara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domeniu', models.CharField(choices=[('flo', 'florarie'), ('dec', 'decorator florist'), ('hot', 'hoteluri / restaurante'), ('org', 'organizatori evenimente'), ('ing', 'ingrijire morminte'), ('gra', 'gradinari'), ('ame', 'amenajari interioare'), ('pre', 'prestari servicii'), ('arh', 'arhitectura peisagistica'), ('des', 'design'), ('alt', 'altele')], max_length=3)),
            ],
        ),
    ]
