# Generated by Django 4.0.5 on 2022-07-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0007_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='denumire_firma',
            field=models.CharField(default='', max_length=250),
        ),
    ]
