# Generated by Django 4.0.5 on 2022-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0008_client_denumire_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='strada',
            field=models.CharField(default='', max_length=250),
        ),
    ]
