# Generated by Django 4.0.5 on 2022-07-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0010_remove_client_domeniu'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cod_p',
            field=models.CharField(default='', max_length=250),
        ),
    ]
