# Generated by Django 4.0.5 on 2022-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0014_client_doresc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='CUI',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='banca',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='cont_bancar',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='reg_comertului',
            field=models.CharField(default='', max_length=250),
        ),
    ]
