# Generated by Django 4.0.5 on 2022-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0015_client_cui_client_banca_client_cont_bancar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_dob',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_fore',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_n',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='owner_dob',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='owner_fore',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='owner_n',
            field=models.CharField(default='', max_length=250),
        ),
    ]
