# Generated by Django 4.0.5 on 2022-08-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0016_client_contact_dob_client_contact_fore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_dob',
            new_name='admin_data_nasterii',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact_fore',
            new_name='admin_nume',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact_n',
            new_name='admin_prenume',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='owner_dob',
            new_name='contact_data_nasterii',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='owner_fore',
            new_name='contact_nume',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='owner_n',
            new_name='contact_prenume',
        ),
    ]
