# Generated by Django 4.0.5 on 2022-08-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine_room', '0017_rename_contact_dob_client_admin_data_nasterii_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
